### PR TITLE
Merging branch into main

### PR DESCRIPTION
**Pull request by Jeyandh**
Hi Shiva, I have uploaded my project. Could you please review for any errors.

### CODE REVIEW

**Comment by Shiva-Rz** [comment]
Hi Jeyandh, I reviwed your backend part 
In the loan controller please follow the coding standards

**Comment by Jeyandh** [comment]
I changed those names shiva. Is there any other issues.

**Comment by Shiva-Rz** [comment]
In the backend part, please add the service annotation in loan.service file.

**Comment by Jeyandh** [comment]
I added that shiva.

**Comment by Shiva-Rz** [comment]
In the loan.java file, please follow the coding standards

**Comment by Jeyandh** [comment]
Yeah Shiva I changed that also.

**Comment by Shiva-Rz** [comment]
That's it for Backend.
In the Frontend part please remove the unwanted tags in the files

**Comment by Jeyandh** [comment]
I have updated that Shiva, any other changes.

**Comment by Shiva-Rz** [comment]
That's it Thank you Jeyandh

**Comment by Jeyandh** [comment]
Thanks for your help Shiva.

**Pull request merged**
